In [1]:
import numpy as np
import pandas as pd

# Numpy

In [10]:
a1 = np.arange(10)
a1.shape

(10,)

In [13]:
a2 = np.arange(0, 10, 2) # On va de 0 a 10 par pas de 2
a2

array([0, 2, 4, 6, 8])

In [26]:
a3 = np.zeros(3)
a3

array([0., 0., 0.])

In [30]:
a4 = np.eye(4) #Matrice identité
a4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
list1 = np.arange(1,6,1)
list2 = np.arange(6,11,1)
list3 = np.arange(12, 22, 2)
r = np.array([list1, list2, list3])
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20]])

In [40]:
r[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20]])

In [43]:
r[1:] #Prend tout a partir de la premiere ligne

array([[ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20]])

In [45]:
r[:1] #Ne prend que la premiere ligne

array([[1, 2, 3, 4, 5]])

In [48]:
r[:,:1] #Idem, ne prend que la premiere colonnne

array([[ 1],
       [ 6],
       [12]])

In [50]:
r[:,2:] #Prend a partir de la 2e colonne, avec la 2e colonne exclue

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [16, 18, 20]])

In [51]:
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20]])

In [68]:
r[2,1:3]

array([14, 16])

In [69]:
r[1:3, :3]

array([[ 6,  7,  8],
       [12, 14, 16]])

In [79]:
r[-2:,-2:]

array([[ 9, 10],
       [18, 20]])

In [87]:
x = np.array([2,3])
y = np.array([4,2])
z = np.add(x, y)
z

array([6, 5])

In [94]:
x - y

array([-2,  1])

In [95]:
x * y

array([8, 6])

In [98]:
x / y

array([0.5, 1.5])

In [99]:
names = np.array(['Anne','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

In [101]:
bm1 = weights / heights ** 2
bm1

array([28.88888889, 14.51836889, 23.046875  ])

In [106]:
#Très bonne façon de faire des eindexations avec des conditions également
print("Overweight ", names[bm1 > 25])
print("Underweight ", names[bm1 < 18.5])
print("Normalweight ", names[(bm1 <= 25) & (bm1 >= 18.5)])

Overweight  ['Anne']
Underweight  ['Joe']
Normalweight  ['Mark']
